platform:
    - x64

environment:
    global:
        CYG_MIRROR: http://cygwin.uib.no
        CYG_CACHE: C:/cygwin/var/cache/setup
    matrix:
        -   CYG_ROOT: C:/cygwin
        -   CYG_ROOT: C:/cygwin64
init:
    - 'echo System architecture: %PLATFORM%'

install:
    - 'appveyor DownloadFile http://cygwin.com/setup-x86.exe -FileName setup-x86.exe'
    - 'setup-x86.exe -qnNdO -R "C:/cygwin" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P wget  -P dos2unix -P diffutils -P cpio -P make -P patch -P mingw64-i686-gcc-core -P mingw64-i686-gcc-g++ >NUL'
    - 'C:/cygwin/bin/bash -lc "cygcheck -dc cygwin"'
    - 'C:/cygwin/bin/bash -lc "wget -q http://ml.ignorelist.com/wodi/8/wodi32.tar.xz -O /tmp/wodi32.tar.xz"'
    - 'C:/cygwin/bin/bash -lc "cd /tmp && rm -rf wodi32 && tar -xf wodi32.tar.xz && bash wodi32/install.sh"'
    - 'C:/cygwin/bin/bash -lc "godi_add godi-ounit"'

    - 'appveyor DownloadFile http://cygwin.com/setup-x86_64.exe -FileName setup-x86_64.exe'
    - 'setup-x86_64.exe -qnNdO -R "C:/cygwin64" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P wget  -P dos2unix -P diffutils -P cpio -P make -P patch -P mingw64-x86_64-gcc-core -P mingw64-x86_64-gcc-g++ >NUL'
    - 'C:/cygwin64/bin/bash -lc "cygcheck -dc cygwin"'
    - 'C:/cygwin64/bin/bash -lc "wget -q http://ml.ignorelist.com/wodi/8/wodi64.tar.xz -O /tmp/wodi64.tar.xz"'
    - 'C:/cygwin64/bin/bash -lc "cd /tmp && rm -rf wodi64 && tar -xf wodi64.tar.xz && bash wodi64/install.sh"'
    - 'C:/cygwin64/bin/bash -lc "godi_add godi-ounit"'

build_script:
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && ./appveyor/build.sh"'

artifacts:
  - path: test.log
    name: test-logs
