# -*- Makefile -*-

.SECONDARY:

ifneq (,$(filter mingw%,$(OSYSTEM)))
lib_process=-lpsapi
ifeq ($(DEBUG),false)
  CFLAGS=-std=c99 -Wall -O3 $(OCAML_FFI_INCOPTS)
else
  CFLAGS=-std=c99 -Wall -g $(OCAML_FFI_INCOPTS)
endif
else
ifeq ($(DEBUG),false)
  CFLAGS=-fPIC -Wall -O3 $(OCAML_FFI_INCOPTS)
else
  CFLAGS=-fPIC -Wall -g $(OCAML_FFI_INCOPTS)
endif
endif

ifeq ($(DEBUG),false)
  OCAMLFLAGS=
else
  OCAMLFLAGS=-g
endif

C_SOURCE  = $(sort $(wildcard $($(PROJECT).dir)/*.c) $(patsubst %,$($(PROJECT).dir)/%,$($(PROJECT).extra_cs)))
ML_SOURCE = $(shell $(OCAMLDEP) -sort $(sort $(wildcard $($(PROJECT).dir)/*.ml) \
                    $(patsubst %,$($(PROJECT).dir)/%,$($(PROJECT).extra_mls))))

NATIVE_OBJECTS = $(ML_SOURCE:$($(PROJECT).dir)/%.ml=$(BUILDDIR)/$($(PROJECT).dir)/%.cmx)
BYTE_OBJECTS = $(ML_SOURCE:$($(PROJECT).dir)/%.ml=$(BUILDDIR)/$($(PROJECT).dir)/%.cmo)
C_OBJECTS = $(C_SOURCE:$($(PROJECT).dir)/%.c=$(BUILDDIR)/$($(PROJECT).dir)/%.o)

STUB_LIB = $(if $(C_OBJECTS),$(BUILDDIR)/dll$(PROJECT)_stubs$(EXTDLL))

CMO_OPTS = $($(PROJECT).cmo_opts)
CMX_OPTS = $($(PROJECT).cmx_opts)
CMA_OPTS = $(if $(C_OBJECTS),-cclib -l$(PROJECT)_stubs -dllib -l$(PROJECT)_stubs)
SUBPROJECT_DEPS = $($(PROJECT).subproject_deps)
LOCAL_CMXAS = $(SUBPROJECT_DEPS:%=$(BUILDDIR)/%.cmxa)
CMXA_OPTS = $(if $(C_OBJECTS),-cclib -l$(PROJECT)_stubs)

OCAMLINCLUDES = -I $(BUILDDIR)/$($(PROJECT).dir) \
                $(foreach spdep,$($(PROJECT).subproject_deps),\
                          -I $(BUILDDIR)/$($(spdep).dir))
NATIVE_LIB=$(BUILDDIR)/$(PROJECT).cmxa
NATIVE_TARGET=$(BUILDDIR)/$(PROJECT).native
LIB_TARGETS = $(BUILDDIR)/$(PROJECT).cma \
              $(STUB_LIB) \
              $(BUILDDIR)/$(PROJECT).cmxa \
              $(BUILDDIR)/$(PROJECT).cmxs
LIB_TARGET_EXTRAS = $(if $(STUB_LIB),$(BUILDDIR)/lib$(PROJECT)_stubs.a) \
                    $(BUILDDIR)/$(PROJECT).a
INSTALL_CMIS = $($(PROJECT).public:%=$(BUILDDIR)/$($(PROJECT).dir)/%.cmi)
INSTALL_MLIS = $($(PROJECT).public:%=$($(PROJECT).dir)/%.mli)
INSTALL_HEADERS = $(wildcard $($(PROJECT).dir)/*.h)
THREAD_FLAG = $(if $(filter yes,$($(PROJECT).threads)),-thread)
LINK_FLAGS = $(as_needed_flags) $($(PROJECT).link_flags)
OCAML_LINK_FLAGS=$(LINK_FLAGS:%=-cclib %)
OCAMLMKLIB_FLAGS=$($(PROJECT).link_flags)
OCAMLFIND_PACKAGE_FLAGS=$(patsubst %,-package %,$($(PROJECT).deps)) \
                        $(patsubst %,-thread -package threads,$(THREAD_FLAG))

$(BUILDDIR)/%.cmxa: $$(NATIVE_OBJECTS)
	$(OCAMLFIND) opt -a -linkall $(OCAMLFLAGS) $(THREAD_FLAG) $(OCAMLFIND_PACKAGE_FLAGS) $(CMXA_OPTS) -o $@ $(NATIVE_OBJECTS) $(OCAML_LINK_FLAGS)

$(BUILDDIR)/dll%_stubs$(EXTDLL): $$(C_OBJECTS)
	$(OCAMLMKLIB) -o $(BUILDDIR)/$*_stubs $^ $(OCAMLMKLIB_FLAGS)

$(BUILDDIR)/%.cmxs : $$(NATIVE_OBJECTS)
	$(OCAMLFIND) opt -shared -linkall $(OCAMLFLAGS) $(THREAD_FLAG) $(OCAMLFIND_PACKAGE_FLAGS) -o $@ $(NATIVE_OBJECTS) $(C_OBJECTS) $(OCAML_LINK_FLAGS)

$(BUILDDIR)/%.cma: $$(BYTE_OBJECTS)
	$(OCAMLFIND) ocamlc -a $(OCAMLFLAGS) $(THREAD_FLAG) $(CMA_OPTS) $(OCAMLFIND_PACKAGE_FLAGS) -o $@ $(BYTE_OBJECTS) $(OCAML_LINK_FLAGS)

$(BUILDDIR)/%.cmo : %.ml
	@mkdir -p $(@D)
	$(OCAMLFIND) ocamlc $(OCAMLFIND_PACKAGE_FLAGS) $(OCAMLFLAGS) $(THREAD_FLAG) $(CMO_OPTS) -c -o $@ $(OCAMLINCLUDES) $<

$(BUILDDIR)/%.cmx : %.ml
	@mkdir -p $(@D)
	$(OCAMLFIND) opt -c -o $@ $(OCAMLFIND_PACKAGE_FLAGS) $(OCAMLFLAGS) $(THREAD_FLAG) $(OCAMLFIND_PACKAGE_FLAGS) $(CMX_OPTS) $(OCAMLINCLUDES) $(filter %.ml,$<)

$(BUILDDIR)/%.o : %.c
	@mkdir -p $(@D)
	cd $(@D) && $(OCAMLFIND) ocamlc -c $(CFLAGS:%=-ccopt %) -o $(@F) $(OCAMLFLAGS) $(realpath $<)

$(BUILDDIR)/%.cmi : %.mli
	@mkdir -p $(@D)
	$(OCAMLFIND) ocamlc -c -o $@ $(OCAMLFIND_PACKAGE_FLAGS) $(OCAMLFLAGS) $(OCAMLINCLUDES) $<

$(BUILDDIR)/%.native : $$(NATIVE_OBJECTS) $$(C_OBJECTS)
	$(OCAMLFIND) opt -I $(BUILDDIR) -linkpkg $(OCAMLFLAGS) $(THREAD_FLAG) $(OCAMLFIND_PACKAGE_FLAGS) $(LOCAL_CMXAS) -o $@ $(NATIVE_OBJECTS) $(C_OBJECTS) $(OCAML_LINK_FLAGS) 
